functionality = {
    "No Intent Detected": "/",
    "Add Policy": "/add-policy",
    "Add Health Policy": "/add-policy/health",
    "Add Corporate Health Policy": "/add-policy/health?type=corporate",
    "Add Retail Health Policy": "/add-policy/health?type=retail",
    "Add Vehicle Policy": "/add-policy/vehicle",
    "Add Travel Policy": "/add-policy/travel",
    "Add Home Policy": "/add-policy/home",

    "Buy Health Insurance": "/buy-policy/health",
    "Buy Elevate": "/buy-policy/health/elevate",
    "Buy MaxProtect": "/buy-policy/health/maxprotect",
    "Buy Active Booster Combo": "/buy-policy/health/active-booster-combo",
    "Buy Active Booster": "/buy-policy/health/active-booster",
    "Buy Health AdvantEdge": "/buy-policy/health/advantEdge",

    "View Health Policies": "/buy-policy/health",
    "View Vehicle Policies": "/buy-policy/car",
    "View Car Policies": "/buy-policy/car",
    "View Bike Policies": "/buy-policy/bike",
    "View Travel Policies": "/buy-policy/travel",
    "View Home Policies": "/buy-policy/home-policy",

    "Buy Car Insurance": "/buy-policy/car",
    "Buy Bike Insurance": "/buy-policy/bike",
    "Buy Travel Insurance": "/buy-policy/travel",
    "Buy Home Insurance": "/buy-policy/home",

    "Face Scan": "/face-scan",
    "Driving Score": "/driving-score",
    "View Challans": "/benefits/motor",
    "Driving Licence": "/benefits/motor",
    "PUC Validity": "/benefits/motor",
    "IL DriveSmart": "/benefits/motor",
    "Motor Self Inspection": "/benefits/motor",

    "Steps": "/benefits/health",
    "Health Records": "/benefits/health",
    "View Health Quotient": "/benefits/health",
    "ABHA Id": "/benefits/health",
    "Track Health": "/benefits/health",

    "Manage Documents": "/benefits/featured",
    "Blogs": "/blogs",
    "Ayurveda Blogs": "/blogs/ayurveda-hub",
    "Wellness Blogs": "/blogs/wellness-blogs",
    "Motor news": "/blogs/motor-news",
    "FAQs": "/help/faqs",
    "RIA": "/help/ria",
}